"use client";

import { useState } from "react";
import { CountUp } from "./CountUp";
import { PILLAR_META } from "@/lib/pillar-meta";
import {
  PILLAR_KEYS,
  PILLAR_LABELS,
  type Completeness,
  type Evidence,
  type PillarKey,
  type Report,
} from "@climate/contract";

const BADGE_CLASS: Record<Completeness, string> = {
  "Well-substantiated": "badge badge-strong",
  "Partial / Vague": "badge badge-partial",
  Missing: "badge badge-missing",
};

function formatDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" });
}

export function ReportView({ report }: { report: Report }) {
  const byId = new Map(report.evidence.map((e) => [e.id, e]));
  const labelFor = new Map(report.documents.map((d) => [d.filename, d.label]));

  return (
    <article className="report">
      <header className="report-masthead rise">
        <p className="report-kicker">Climate Disclosure Readiness Assessment · AASB S2 / TCFD</p>
        <h1 className="report-company">{report.company_name}</h1>
        <p className="report-dateline">
          Prepared {formatDate(report.generated_at)} from {report.documents.length}{" "}
          {report.documents.length === 1 ? "document" : "documents"} provided by the company
        </p>
      </header>

      <div className="report-lede report-block rise" style={{ ["--i" as string]: 1 }}>
        <p className="report-summary">{report.executive_summary}</p>
        <div className="score-block">
          <span className="score-value">
            <CountUp value={report.overall_readiness_score} duration={1100} />
            <span className="score-denom">/100</span>
          </span>
          <div className="score-caption">Overall readiness</div>
        </div>
      </div>

      <h2 className="section-rule">Assessment by pillar</h2>
      {PILLAR_KEYS.map((key, i) => {
        const pillar = report.pillars[key];
        if (!pillar) return null;
        return (
          <PillarSection
            key={key}
            pillarKey={key}
            index={i}
            score={pillar.score}
            completeness={pillar.completeness}
            narrative={pillar.narrative}
            evidence={pillar.evidence_ids.map((id) => byId.get(id)).filter((e): e is Evidence => !!e)}
            labelFor={labelFor}
          />
        );
      })}

      {report.findings.length > 0 && (
        <section className="report-block">
          <h2 className="section-rule">Findings</h2>
          <div className="findings">
            {report.findings.map((f) => (
              <div className="finding" key={f.id}>
                <div className="finding-pillar">{PILLAR_LABELS[f.pillar]}</div>
                <div className="finding-body">
                  <p className="finding-summary">{f.summary}</p>
                  <span className={BADGE_CLASS[f.type]} style={{ alignSelf: "flex-start" }}>
                    {f.type}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {report.recommendations.length > 0 && (
        <section className="report-block">
          <h2 className="section-rule">Recommendations</h2>
          <div className="recs">
            {report.recommendations.map((r, i) => (
              <div className="rec" key={`${r.pillar}-${i}`}>
                <div>
                  <p className="rec-pillar">{PILLAR_LABELS[r.pillar]}</p>
                  <p className="rec-text">{r.text}</p>
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      <section className="report-block">
        <h2 className="section-rule">Source documents</h2>
        <div className="sources">
          {report.documents.map((d) => {
            const count = report.evidence.filter((e) => e.document === d.filename).length;
            return (
              <div className="source" key={d.filename}>
                <span className="source-file">{d.filename}</span>
                <span className="source-label">{d.label}</span>
                <span className="source-count">
                  {count} {count === 1 ? "item" : "items"} of evidence
                </span>
              </div>
            );
          })}
        </div>
      </section>

      <p className="report-colophon">
        Generated by GreenScreened from automated analysis of the documents listed above. Every
        assessment in this
        report is traceable to cited evidence; a pillar rated Missing indicates that no supporting
        evidence was found in the documents provided, which is not necessarily evidence that the
        underlying practice is absent.
      </p>
    </article>
  );
}

function PillarSection({
  pillarKey,
  index,
  score,
  completeness,
  narrative,
  evidence,
  labelFor,
}: {
  pillarKey: PillarKey;
  index: number;
  score: number;
  completeness: Completeness;
  narrative: string;
  evidence: Evidence[];
  labelFor: Map<string, string>;
}) {
  const [open, setOpen] = useState(false);

  const { colorVar, Icon } = PILLAR_META[pillarKey];

  return (
    <section
      className="report-pillar rise"
      style={{ ["--i" as string]: index, borderLeftColor: colorVar }}
    >
      <div className="pillar-head">
        <h3 className="pillar-name">
          <span className="pillar-icon" style={{ color: colorVar }}>
            <Icon />
          </span>
          {PILLAR_LABELS[pillarKey]}
        </h3>
        <div className="pillar-metrics">
          <span className={BADGE_CLASS[completeness]}>{completeness}</span>
          <span className="pillar-score">
            <CountUp value={score} duration={850} />
            <span>/100</span>
          </span>
        </div>
      </div>

      <div className="pillar-bar">
        <i style={{ width: `${score}%` }} />
      </div>

      <p className="pillar-narrative">{narrative}</p>

      {evidence.length === 0 ? (
        <p className="citations-empty">No supporting evidence was found for this pillar.</p>
      ) : (
        <>
          <button
            className="citations-toggle no-print"
            aria-expanded={open}
            onClick={() => setOpen((v) => !v)}
          >
            <span className="chev">▶</span>
            {open ? "Hide" : "Show"} {evidence.length} cited{" "}
            {evidence.length === 1 ? "source" : "sources"}
          </button>

          {/* Always rendered, hidden via the `hidden` attribute, so the print
              stylesheet can reveal every citation in the exported PDF. */}
          <div className="citations" hidden={!open}>
            {evidence.map((e) => (
              <div className="citation" key={e.id}>
                <p className="citation-claim">{e.claim}</p>
                <div className="citation-source">
                  <span className="citation-id">{e.id}</span>
                  <span>
                    {e.document} · page {e.page}
                  </span>
                  <span>{labelFor.get(e.document) ?? ""}</span>
                </div>
                {e.raw_text_snippet && <p className="citation-snippet">“{e.raw_text_snippet}”</p>}
              </div>
            ))}
          </div>
        </>
      )}
    </section>
  );
}
