// Granular evidence checks, not an exhaustive legal-compliance checklist.
// Descriptions paraphrase the user's requirements; references identify review sources.
const groups = {
  governance: [
    ["responsibleBody", "Responsible climate governance body or individuals", "6(a)(i)"],
    ["responsibilities", "Documented climate responsibilities and mandates", "6(a)(i)"],
    ["competencies", "Climate skills and competencies", "6(a)(ii)"],
    ["informationFlow", "How and how often climate information reaches the governing body", "6(a)(iii)"],
    ["decisions", "Climate considerations in strategy and major decisions", "6(a)(iv)"],
    ["targetOversight", "Oversight of climate targets and progress", "6(a)(v)"],
    ["managementRole", "Management climate responsibilities", "6(b)(i)"],
    ["controls", "Climate governance controls and procedures", "6(b)(ii)"],
    ["remuneration", "Climate target links to remuneration, or explicit disclosure that none exist", "6(a)(v)"],
  ],
  strategy: [
    ["identifiedRisks", "Identified climate-related risks", "10(a)"],
    ["identifiedOpportunities", "Identified climate-related opportunities", "10(a)"],
    ["riskClassification", "Classification of climate risks as physical or transition", "10(b)"],
    ["timeHorizons", "Short, medium and long-term horizons for risks and opportunities", "10(c)"],
    ["horizonDefinitions", "Definitions of time horizons linked to planning", "10(d)"],
    ["businessModel", "Current and anticipated effects on the business model", "13"],
    ["valueChain", "Current and anticipated effects across the value chain", "13"],
    ["responses", "Climate strategy and decision-making responses", "14(a)"],
    ["transitionPlan", "Transition plans, dependencies and assumptions where applicable", "14(a)(iv)"],
    ["resourceAllocation", "Resource allocation and capital decisions for climate responses", "14(b)"],
    ["currentFinancialEffects", "Current climate-related financial effects", "15(a),16"],
    ["anticipatedFinancialEffects", "Anticipated climate-related financial effects", "15(b),16"],
    ["financialPlanning", "Connections to financial planning and funding", "16(c)-(d)"],
    ["resilience", "Climate resilience assessment and implications", "22(a)"],
    ["scenarioAnalysis", "Scenario analysis inputs, assumptions, scenarios, timing and results", "22(b),Aus22.1"],
  ],
  riskManagement: [
    ["identification", "Processes for identifying climate risks", "25(a)"],
    ["assessment", "Climate risk assessment processes", "25(a)"],
    ["prioritisation", "Prioritisation of climate risks relative to other risks", "25(a)(iv)"],
    ["monitoring", "Monitoring climate risks and changes to processes", "25(a)(v)-(vi)"],
    ["inputs", "Data sources, inputs and parameters used in risk processes", "25(a)(i)"],
    ["scenarioUse", "Whether and how scenario analysis informs climate risk identification", "25(a)(ii)"],
    ["likelihoodMagnitude", "Assessment of likelihood and magnitude of climate effects", "25(a)(iii)"],
    ["opportunityProcesses", "Processes for climate-related opportunities", "25(b)"],
    ["enterpriseIntegration", "Integration of climate processes into enterprise risk management", "25(c)"],
  ],
  metricsAndTargets: [
    ["scope1", "Scope 1 GHG emissions with period, units and boundary", "29(a)(i)"],
    ["scope2", "Scope 2 GHG emissions with period, units, boundary and location-based information", "29(a)(i),(v)"],
    ["scope3", "Scope 3 GHG emissions with period, units and boundary", "29(a)(i),(vi)"],
    ["methodology", "Emissions measurement approach and methodology", "29(a)(ii)-(iii)"],
    ["assumptionsQuality", "Emissions assumptions, inputs and data quality", "29(a)(iii),B38-B57"],
    ["scope3Categories", "Scope 3 categories and measurement coverage", "29(a)(vi)"],
    ["transitionRiskExposure", "Amounts and percentages of assets or activities exposed to transition risk", "29(b)"],
    ["physicalRiskExposure", "Amounts and percentages of assets or activities exposed to physical risk", "29(c)"],
    ["climateOpportunityExposure", "Amounts and percentages aligned with climate opportunities", "29(d)"],
    ["capitalDeployment", "Capital expenditure, financing or investment for climate risks and opportunities", "29(e)"],
    ["internalCarbonPrice", "Whether carbon pricing is used; its application and price if used", "29(f)"],
    ["executiveRemuneration", "Whether and how executive remuneration considers climate, including relevant percentage", "29(g)"],
    ["targets", "Climate-related targets and objectives", "33(a)-(b)"],
    ["basePeriods", "Target base periods", "33(e)"],
    ["targetPeriods", "Periods over which targets apply", "33(d)"],
    ["milestones", "Interim target milestones", "33(f)"],
    ["targetBasis", "Whether targets are absolute or intensity-based", "33(g)"],
    ["progress", "Performance and progress against climate targets", "35"],
    ["targetMethods", "Methods to set, validate, review and monitor targets", "34"],
  ],
  generalRequirements: [
    ["materiality", "Documented materiality assessment and its basis", "D17-D19"],
    ["fairPresentation", "Evidence sufficiency and fair-presentation review", "D11-D16"],
    ["reportingEntityConsistency", "Reporting-entity consistency with financial statements", "D20"],
    ["connectedInformation", "Connections among climate-related disclosures", "D21-D24"],
    ["financialStatementConnections", "Connections to related financial statements", "D21-D24"],
    ["reportingPeriod", "Reporting period and alignment of disclosure timing", "D64-D69"],
    ["judgements", "Significant judgements and their basis", "D74-D76"],
    ["measurementUncertainty", "Measurement uncertainty and significant estimation assumptions", "D77-D82"],
    ["comparatives", "Comparable prior-period information unless confirmed relief applies", "D70-D71,C3"],
    ["transitionReliefs", "Disclosure of applicable transition reliefs and their basis", "C3-C5"],
    ["metricConsistency", "Consistency of metrics over time and explained changes", "D51-D53"],
    ["metricSources", "Metric sources, definitions and methodologies", "D49-D50"],
  ],
};
export const aasbRubric = Object.entries(groups).flatMap(([section, entries]) => entries.map(([key, description, reference]) => ({
  id: `${section}.${key}`, section, key, description, reference,
})));
export const statuses = ["present", "partial", "missing", "not_applicable", "requires_human_judgement"];
export const responseJsonSchema = {
  type: "object", required: ["assessments"], additionalProperties: false,
  properties: { assessments: { type: "array", items: {
    type: "object", required: ["criterionId", "status", "citations"], additionalProperties: false,
    properties: {
      criterionId: { type: "string", enum: aasbRubric.map(r => r.id) },
      status: { type: "string", enum: statuses },
      citations: { type: "array", items: { type: "object", required: ["evidenceId", "quote"], additionalProperties: false,
        properties: { evidenceId: { type: "string" }, quote: { type: "string" } } } },
    },
  } } },
};
